theme: jekyll-theme-minimal
title: [Hariharan Ravishankar]
github:
  is_project_page: false
logo: "photo.jpg" width="100" height="100"
author:
  name             : "MISP Standard"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : ""
  location         : "International"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: hariharanrav@iisc.ac.in
