theme: jekyll-theme-minimal
title: [Hariharan Ravishankar]
github:
  is_project_page: false

links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: hariharanrav@iisc.ac.in
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://hariharanrav.github.io/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/MISPProject"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"
